function est=VB3_parameterEstimates(M)
% est=VB3_parameterEstimates(M)
% generate some estimates based on a M-field. Good for interpreting various
% 'true' models, e.g., those generated by knowing the hidden states etc.
% M : input M field of some model
% est : those parameter estiomates that can be done based on the M field
% alone, same as done by VB3_VBEMiterator

% M.L. 2012-07-05





% global light-weight estimates (always)
est.Amean=zeros(size(M.wA));
est.Astd=zeros(size(M.wA));
est.Amode=zeros(size(M.wA));
a0=sum(M.wA,2);
for k=1:N
    est.Amean(k,:)=M.wA(k,:)/a0(k);
    est.Astd(k,:)=sqrt((M.wA(k,:).*(a0(k)-M.wA(k,:)))./(a0(k)^2*(1+a0(k))));
    est.Amode(k,:)=(M.wA(k,:)-1)/(a0(k)-N);
end

est.dwellMean=1./(1-diag(est.Amean));
est.dwellMode=1./(1-diag(est.Amode));
% emission parameters
est.gMean=M.n./M.c;
est.gMode=(M.n-1)./M.c;
est.gStd=sqrt(M.n./M.c.^2); % sqrt(Var(g))
est.DdtMean=M.c/4./(M.n-1);
est.DdtMode=M.c/4./(M.n+1);
est.Ddtstd=M.c/4./(M.n-1)./sqrt(M.n-2);
